"""Named constants for the Script Server application."""

# WebSocket
WEBSOCKET_PING_INTERVAL_SECONDS = 30
WEBSOCKET_PING_TIMEOUT_SECONDS = 300
WEBSOCKET_CLOSE_TIMEOUT_SECONDS = 5
WEBSOCKET_NORMAL_CLOSE_CODE = 1000

# Server defaults
DEFAULT_HTTP_PORT = 5000
DEFAULT_HTTPS_PORT = 5443
DEFAULT_PROXY_PORT = 3128

# Limits
MAX_LOG_LINES = 10000

# Scheduling
SCHEDULE_CLEANUP_INTERVAL_SECONDS = 300
MAX_SCHEDULE_ITERATIONS = 10000

# File management
FILE_RETENTION_MS = 1000 * 60 * 60 * 24  # 24 hours in milliseconds

# LDAP
LDAP_CONNECT_TIMEOUT_SECONDS = 10
