<template>
  <div class="verb-option-editor">
    <div class="row">
      <TextField
        v-model="option.name"
        :config="nameField"
        class="col s4"
        @error="emitError('name', $event)"
      />
      <TextField
        v-model="option.label"
        :config="labelField"
        class="col s4"
        @error="emitError('label', $event)"
      />
    </div>

    <div class="row">
      <TextArea
        v-model="option.description"
        :config="descriptionField"
        class="col s12"
      />
    </div>
  </div>
</template>

<script>
import TextField from '@/common/components/textfield';
import TextArea from '@/common/components/TextArea';
import {isEmptyString} from '@/common/utils/common';

export default {
  name: 'VerbOptionEditor',

  components: {
    TextField,
    TextArea
  },

  props: {
    option: {
      type: Object,
      required: true
    }
  },

  data() {
    return {
      nameField: {
        name: 'Verb Name',
        required: true,
        description: 'CLI value (e.g., "create", "delete")'
      },
      labelField: {
        name: 'Label',
        description: 'Display text shown in UI (e.g., "Create Item")'
      },
      descriptionField: {
        name: 'Description',
        description: 'Help text shown when verb is selected'
      }
    };
  },

  methods: {
    emitError(fieldName, message) {
      this.$emit('error', {fieldName, message});
    }
  },

  watch: {
    'option.name'(newName, oldName) {
      // Auto-fill label if it was auto-generated or empty
      const oldAutoLabel = oldName ? oldName.charAt(0).toUpperCase() + oldName.slice(1) : '';
      const isLabelAutoGenerated = isEmptyString(this.option.label) || this.option.label === oldAutoLabel;

      if (isLabelAutoGenerated && !isEmptyString(newName)) {
        this.$set(this.option, 'label', newName.charAt(0).toUpperCase() + newName.slice(1));
      }
    }
  }
};
</script>

<style scoped>
.verb-option-editor {
  padding: 12px;
}

.section-label {
  font-size: 14px;
  font-weight: 500;
  color: var(--font-color-main, #fff);
  margin-bottom: 4px;
  display: block;
}

.helper-text {
  font-size: 12px;
  color: var(--font-color-medium, rgba(255, 255, 255, 0.7));
  margin-top: 0;
  margin-bottom: 12px;
}

/* Fix input field visibility */
.verb-option-editor >>> input[type="text"],
.verb-option-editor >>> textarea {
  background: #fff !important;
  color: #333 !important;
  border: 1px solid #ddd !important;
}

.verb-option-editor >>> input[type="text"]:focus,
.verb-option-editor >>> textarea:focus {
  border-color: #2196F3 !important;
  outline: none;
}

.verb-option-editor >>> .input-field label {
  color: #666 !important;
}

.verb-option-editor >>> .input-field label.active {
  color: #2196F3 !important;
}
</style>
